/*
 * This file is part of eyeo Chromium SDK,
 * Copyright (C) 2006-present eyeo GmbH
 *
 * eyeo Chromium SDK is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 3 as
 * published by the Free Software Foundation.
 *
 * eyeo Chromium SDK is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with eyeo Chromium SDK.  If not, see <http://www.gnu.org/licenses/>.
 */

// Generated by chrome/tools/build/sha256_file.py
// !! DO NOT EDIT !!

#include <stdint.h>

#include <array>

#ifndef GEN_COMPONENTS_ADBLOCK_CORE_HASH_SCHEMA_HASH_H_
#define GEN_COMPONENTS_ADBLOCK_CORE_HASH_SCHEMA_HASH_H_

extern const std::array<uint8_t, 32> kSha256_filter_list_schema_generated_h;

#endif  // GEN_COMPONENTS_ADBLOCK_CORE_HASH_SCHEMA_HASH_H_
