caption: Settings for Generative AI Photo Editing feature
desc: |-
  This policy controls the settings of the Generative AI Photo Editing feature for <ph name="PRODUCT_OS_NAME">$1<ex>Google ChromeOS</ex></ph>.

  0 = Enable the feature for users, and send relevant data to Google to help train or improve AI models. Relevant data may include prompts, inputs, outputs, and source materials, depending on the feature. It may be reviewed by humans for the sole purpose of improving AI models. 0 is the default value, except when noted below.

  1 = Enable the feature for users, but do not send data to Google to train or improve AI models. 1 is the default value for Enterprise users managed by <ph name="GOOGLE_ADMIN_CONSOLE_PRODUCT_NAME">Google Admin console</ph> and for Education accounts managed by <ph name="GOOGLE_WORKSPACE_PRODUCT_NAME">Google Workspace</ph>.

  2 = Disable the feature.

default: 0
example_value: 2
features:
  # Policy changes do not require a browser restart. However, the new policy
  # will be applied the next time users open a new photo, not immediately.
  # It is because the user might be actively editing during policy update.
  dynamic_refresh: true
  per_profile: true
owners:
- file://chromeos/ash/components/mantis/OWNERS
items:
- caption: Allow Generative AI Photo Editing and improve AI models.
  name: Allowed
  value: 0
- caption: Allow Generative AI Photo Editing without improving AI models.
  name: AllowedWithoutLogging
  value: 1
- caption: Do not allow Generative AI Photo Editing.
  name: Disabled
  value: 2
schema:
  enum:
  - 0
  - 1
  - 2
  type: integer
future_on:
- chrome_os
tags: []
type: int-enum
