# This file is part of eyeo Chromium SDK,
# Copyright (C) 2006-present eyeo GmbH
# eyeo Chromium SDK is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 3 as
# published by the Free Software Foundation.
# eyeo Chromium SDK is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# You should have received a copy of the GNU General Public License
# along with eyeo Chromium SDK.  If not, see <http://www.gnu.org/licenses/>.

# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
# Motivation to use hooks and internal agreements are discussed here:
# https://confluence.eyeo.com/display/DP/Using+pre-commit+to+make+better+commits
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.27.1
    hooks:
      - id: yamllint
        args: [-d relaxed]
  - repo: https://gitlab.com/smop/pre-commit-hooks.git
    rev: v1.0.0
    hooks:
      - id: check-gitlab-ci
        name: GitLab CI/CD configuration check
        description: Validates .gitlab-ci.yml file
        entry: pre_commit_hooks/check-gitlab-ci
        language: script
        pass_filenames: false
        files: .gitlab-ci.yml
  - repo: git@gitlab.com:eyeo/distpartners/chromium-precommit-hooks.git
    rev: 0cf764023322f48b2d1492e76fe1320cdf3d3ca2
    hooks:
      - id: no-forbidden-words-in-branch-name
      - id: no-forbidden-words-in-diff
      - id: eyeo-license-headers-check
  - repo: "local"
    hooks:
      - id: clang-format
        name: clang-format
        description: Print formatting errors found with ClangFormat.
        entry: "third_party/depot_tools/clang-format"
        language: system
        files: \.(c|cc|cxx|cpp|frag|glsl|h|hpp|hxx|ih|ispc|ipp|java|js|m|mm|proto|textproto|vert)$
        args: ['-fallback-style=none', '-i', '--dry-run', '--Werror']
